<a href="https://colab.research.google.com/github/saikumar540/Neural-Networks/blob/main/700765540_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Base class Employee
class Employee:
    # Class variable to count number of Employees
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1  # Increment employee count whenever a new Employee is created

    def average_salary(self, *employees):
        total_salary = sum(employee.salary for employee in employees)
        average = total_salary / len(employees) if employees else 0
        return average

# Derived class FulltimeEmployee, inheriting from Employee
class FulltimeEmployee(Employee):
    pass

# Create instances of Employee and FulltimeEmployee
emp1 = Employee("Sai Kumar", "Podilapu", 150000, "Manager")
emp2 = Employee("Nithish", "Vunnam", 90000, "Finance")

ft_emp1 = FulltimeEmployee("Naveen", "Peruri", 75000, "HR" )
ft_emp2 = FulltimeEmployee("Vamsi", "Bagadi", 85000, "Engineering")

# Call member functions

avg_sal_for_employees=emp1.average_salary(emp1, emp2)
avg_sal_for_fultime_employees=emp1.average_salary(ft_emp1, ft_emp2)

print("Average_Salary_Employees",avg_sal_for_employees)
print("Average_Salary_FullTime_Employees",avg_sal_for_fultime_employees)


# Show the total number of employees

print("Total number of employees",Employee.employee_count)



Average_Salary_Employees 120000.0
Average_Salary_FullTime_Employees 80000.0
Total number of employees 4


 Numpy Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1) (you can NOT implement it via for loop)

In [1]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 5.69069669 15.40851262  9.23435715  7.6610868   1.58677376 16.62873977
 11.22955857  7.55776694  6.28713306  2.73788717 13.15400009  7.42789184
 11.4296073   4.33438412  3.04168254  9.27092819  5.31556301  1.57684286
  7.49597278  4.97130155]


In [2]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)


[[ 5.69069669 15.40851262  9.23435715  7.6610868   1.58677376]
 [16.62873977 11.22955857  7.55776694  6.28713306  2.73788717]
 [13.15400009  7.42789184 11.4296073   4.33438412  3.04168254]
 [ 9.27092819  5.31556301  1.57684286  7.49597278  4.97130155]]


In [3]:


# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 5.69069669  0.          9.23435715  7.6610868   1.58677376]
 [ 0.         11.22955857  7.55776694  6.28713306  2.73788717]
 [ 0.          7.42789184 11.4296073   4.33438412  3.04168254]
 [ 0.          5.31556301  1.57684286  7.49597278  4.97130155]]


In [ ]:
https://www.loom.com/share/1b17382fe2f44e1aa362133f8294ba9e